name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check TODO comments
        run: |
          # Run a command to find TODO comments in the code
          TODO_COUNT=$(git grep -i TODO | wc -l)
          
          # Check if TODO comments were found
          if [ "$TODO_COUNT" -gt 0 ]; then
            echo "TODO comments found in the code."
            exit 1
          fi
